// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1-qmYt3fwlA-TlHmxHOhd_DL3lmj5TF0',
    appId: '1:249357070035:web:ac5050ebe46fece26e2e26',
    messagingSenderId: '249357070035',
    projectId: 'srisoftwarez-crm',
    authDomain: 'srisoftwarez-crm.firebaseapp.com',
    storageBucket: 'srisoftwarez-crm.firebasestorage.app',
    measurementId: 'G-TFJMX734D4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN9KCExYnJkUGcMgvxr3KnvmJDY4PiPZI',
    appId: '1:249357070035:android:bceadab9dbcac9b86e2e26',
    messagingSenderId: '249357070035',
    projectId: 'srisoftwarez-crm',
    storageBucket: 'srisoftwarez-crm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIWcOw_muSxhkr1SpHin_xBo5RelMV8V8',
    appId: '1:249357070035:ios:2be0d1f0f0a5452a6e2e26',
    messagingSenderId: '249357070035',
    projectId: 'srisoftwarez-crm',
    storageBucket: 'srisoftwarez-crm.firebasestorage.app',
    iosBundleId: 'com.srisoftwarez.aaatp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIWcOw_muSxhkr1SpHin_xBo5RelMV8V8',
    appId: '1:249357070035:ios:7f8ed6d597e36a1d6e2e26',
    messagingSenderId: '249357070035',
    projectId: 'srisoftwarez-crm',
    storageBucket: 'srisoftwarez-crm.firebasestorage.app',
    iosBundleId: 'com.srisoftwarez.aaatp.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1-qmYt3fwlA-TlHmxHOhd_DL3lmj5TF0',
    appId: '1:249357070035:web:2d15a779bcaf48bc6e2e26',
    messagingSenderId: '249357070035',
    projectId: 'srisoftwarez-crm',
    authDomain: 'srisoftwarez-crm.firebaseapp.com',
    storageBucket: 'srisoftwarez-crm.firebasestorage.app',
    measurementId: 'G-QTD7VVDMS2',
  );
}