// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGyZe6crlOPMfMmXvYWiquBCQDfDBmmo8',
    appId: '1:204207195810:web:4f329a51ecefce1f0339fb',
    messagingSenderId: '204207195810',
    projectId: 'leadcapture-79a43',
    authDomain: 'leadcapture-79a43.firebaseapp.com',
    storageBucket: 'leadcapture-79a43.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfQhvOiQ2e_ChtI2e5d8Lc68kQviqssCk',
    appId: '1:204207195810:android:e65d94b37fc20e380339fb',
    messagingSenderId: '204207195810',
    projectId: 'leadcapture-79a43',
    storageBucket: 'leadcapture-79a43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpJYFQN_hwLFBafWn3zdYx1dJ1mE3UtBk',
    appId: '1:204207195810:ios:61ae8bd9237a1df40339fb',
    messagingSenderId: '204207195810',
    projectId: 'leadcapture-79a43',
    storageBucket: 'leadcapture-79a43.firebasestorage.app',
    iosBundleId: 'com.srisoftwarez.leadcapture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpJYFQN_hwLFBafWn3zdYx1dJ1mE3UtBk',
    appId: '1:204207195810:ios:506bd2b6cbef2e170339fb',
    messagingSenderId: '204207195810',
    projectId: 'leadcapture-79a43',
    storageBucket: 'leadcapture-79a43.firebasestorage.app',
    iosBundleId: 'com.srisoftwarez.leadcapture.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGyZe6crlOPMfMmXvYWiquBCQDfDBmmo8',
    appId: '1:204207195810:web:a2372760280e11a90339fb',
    messagingSenderId: '204207195810',
    projectId: 'leadcapture-79a43',
    authDomain: 'leadcapture-79a43.firebaseapp.com',
    storageBucket: 'leadcapture-79a43.firebasestorage.app',
  );

}